name: ci

on: [push, pull_request]

jobs:
  build-windows:

    runs-on: [ windows-latest ]

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
          architecture: x64
      - name: Build with Gradle
        run: .\gradlew.bat assemble
      - name: Create Distribution
        run: .\build_app_windows.bat
      - uses: actions/upload-artifact@v2
        with:
          name: fxmodules Windows
          path: '.\build\installer\fxmodules-17.0.0.msi'



  build-mac:

    runs-on: [ macos-latest ]

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
          architecture: x64
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Grant execute permission for build_app_macos.sh
        run: chmod +x ./build_app_macos.sh
      - name: Create Distribution
        run: ./build_app_macos.sh
      - uses: actions/upload-artifact@v2
        with:
          name: fxmodules Mac
          path: |
            ./build/installer/FXModules-17.0.0.pkg
            ./build/libs/fxmodules-17.0.0.jar

  build-linux:

    runs-on: [ ubuntu-latest ]

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
          architecture: x64
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Grant execute permission for build_app_linux.sh
        run: chmod +x ./build_app_linux.sh
      - name: Create Distribution
        run: ./build_app_linux.sh
      - uses: actions/upload-artifact@v2
        with:
          name: fxmodules Linux
          path: |
            ./build/installer/fxmodules_17.0.0-1_amd64.deb
            ./build/installer/fxmodules-17.0.0-1_x86_64.rpm
            ./build/libs/fxmodules-17.0.0.jar